### ISSUE TITLE
Unexpected version created for fish 2.7.1

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#114]
When I run autospec for fish 2.7.1, the version is detected as "fish.2.7.1", but I would expect it to be "2.7.1".

The upstream URL is https://github.com/fish-shell/fish-shell/releases/download/2.7.1/fish-2.7.1.tar.gz, and the rpm package name is "fish".

**Comment by matthewrsj** [comment]
This is an issue because the name will be detected as `fish-shell` and therefore `fish` will not be removed from the version string. I'm going to say this is a wontfix because the detected name and name in the version string don't match. Versioning will have to be handled manually for this package.
