### ISSUE TITLE
Centos7 : Python : installation failed

### ISSUE THREAD

**Issue by MikeLynx** [clearlinux/autospec#117]
Hello,
` python setup.py install`

Result :
`byte-compiling build/bdist.linux-x86_64/egg/autospec/buildreq.py to buildreq.pyc
  File "build/bdist.linux-x86_64/egg/autospec/buildreq.py", line 571
    print("Buildreqs   : ", end="")
                               ^
SyntaxError: invalid syntax

`

I have no Python 3x installed but only 2.7 ...
Thank you for your feedback and sorry

**Comment by fenrus75** [comment]
are you using python 3.x ?
