### ISSUE TITLE
How to install autospec

### ISSUE THREAD

**Issue by MikeLynx** [clearlinux/autospec#119]
Hello,

I don't understand how to install correctly the tool.
I have done :
python3 setup.py build
python3 setup.py install

No errors but when I try to find autospec nothing ...

Thank you

**Comment by matthewrsj** [comment]
Hi @MikeLynx, if you look at #8, autospec is not useful as an installed package right now. The best way to use it right now is via the https://github.com/clearlinux/common tooling used by the Clear Linux team. What that tooling does is use the python files directly from a cloned autospec repo. See https://github.com/clearlinux/common/blob/master/README.md for steps on how to set this up.

**Comment by matthewrsj** [comment]
There has been a PR open to make autospec installable at #21 for some time, but that will require a careful review and collaboration with the maintainer of the common tooling (@phmccarty) to make sure all of that isn't broken by changing path names.

**Comment by MikeLynx** [comment]
Thank you  a lot I will try to use clearlinux tool.
