### ISSUE TITLE
python requirements enhancement for python3 subpackages

### ISSUE THREAD

**Issue by mrkz** [clearlinux/autospec#129]
At the time of creating this bug, for a python package, autospec creates 3 python sub-packages with the dependencies as the example given:

```
Name     : python-zeep
[...]
Requires: python-zeep-legacypython
Requires: python-zeep-python3
Requires: python-zeep-python
Requires: appdirs                                                    
Requires: cached-property
Requires: defusedxml                                               
Requires: isodate    
Requires: lxml
Requires: pytz
Requires: requests     
Requires: six

[...]

%package legacypython
Summary: legacypython components for the python-zeep package.
Group: Default
Requires: python-core

[...]

%package python
Summary: python components for the python-zeep package.
Group: Default
Requires: python-zeep-legacypython
Requires: python-zeep-python3

[...]

%package python3
Summary: python3 components for the python-zeep package.
Group: Default
Requires: python3-core
[...]

```

Adding the ***-legacypython**/***-python3** Requires of the packages noted by the main package (python-zeep) would be a nice improvement to autospec, as we could easily separate legacypython/python3 packages without having to manually add those deps in the legacypython/python3 bundles manually.

So the expected output would be as follows:
```
Name     : python-zeep
[...]
Requires: python-zeep-legacypython
Requires: python-zeep-python3
Requires: python-zeep-python
Requires: appdirs                                                    
Requires: cached-property
Requires: defusedxml                                               
Requires: isodate    
Requires: lxml
Requires: pytz
Requires: requests     
Requires: six

[...]

%package legacypython
Summary: legacypython components for the python-zeep package.
Group: Default
Requires: python-core
Requires: appdirs-legacypython
Requires: cached-property-legacypython
Requires: defusedxml-legacypython
Requires: isodate-legacypython
Requires: lxml-legacypython
Requires: pytz-legacypython
Requires: requests-legacypython
Requires: six-legacypython

[...]

%package python
Summary: python components for the python-zeep package.
Group: Default
Requires: python-zeep-legacypython
Requires: python-zeep-python3

[...]

%package python3
Summary: python3 components for the python-zeep package.
Group: Default
Requires: python3-core
Requires: appdirs-python3
Requires: cached-property-python3
Requires: defusedxml-python3
Requires: isodate-python3
Requires: lxml-python3
Requires: pytz-python3
Requires: requests-python3
Requires: six-python3
[...]
```

Please notice that now both legacypython and python3 sub-packages Requires the dependencies with the proper version.

**Comment by matthewrsj** [comment]
This seems reasonable to me, @bryteise any comments?

**Comment by mrkz** [comment]
For the record, as we're moving away from legacypython (python2.7), I don't mind having the legacypython part of this enhancement out of the scope :smiley:

**Comment by fenrus75** [comment]
%package python
Summary: python components for the python-zeep package.
Group: Default
Requires: python-zeep-legacypython

'

this is the part we do NOT want.

**Comment by bryteise** [comment]
Yea I like this quite a bit though I'm not sure how much use it will get outside of allowing folks to easily add the full python2 deps by just including the legacypython2 subpackage. Regardless I'm fine with it. As @fenrus75 noted though the python subpackage will be dropping legacypython though.

**Comment by phmccarty** [comment]
@mrkz Is this feature still desired for autospec?

**Comment by phmccarty** [comment]
I removed mention of legacypython in the title, since the python2 content has been split out info deprecated-* packages, and those will disappear soon anyway.

**Comment by mrkz** [comment]
@phmccarty, to be honest, I don't recall the situation I was under when opening this issue, not to mention that python handling in autospec has changed a lot since this issue was created. Taking into account that python2 is to be dropped, I don't think this is relevant anymore as of today, so I'm closing this issue.

Thanks!
