### ISSUE TITLE
Recurse Dependencies?

### ISSUE THREAD

**Issue by shrmrf** [clearlinux/autospec#174]
I'm new to `autospec`, and thus I'm looking for some guidelines into a problem I'm (theoretically going to be) facing...

I create a library (`libprogex`) that I want to install using `autospec` and I create a program (`progex`) that depends on that shared library to build. How can I provide `autospec` the path (URL or whatever) to use _non-upstream_ dependencies (`libprogex` in this case) for building `progex`?

Thanks

**Comment by bryteise** [comment]
So if you are using autospec with the common tooling there is a `repoadd` target which will create a local rpm repository and add the package you just built to it while also creating a mock configuration file that will be used by autospec that references the local repository. If you are not using the common tooling you'll need to copy the binary rpms you built for `libprogex` to a folder you can run createrepo_c on (`mkdir foo && cp libprogex.rpm foo && createrepo_c foo`) then update your mock configuration used by autospec to point to the local repo. That section would be something like:
`[localrepo]
name=Local repo
failovermethod=priority
enabled=1
gpgcheck=0
baseurl=file:///home/user/foo/`

**Comment by phmccarty** [comment]
For reference, the common tooling @bryteise mentioned is from https://github.com/clearlinux/common

**Comment by shrmrf** [comment]
@bryteise and @phmccarty thanks guys... I'll try this out!! I think this solves my problem :)
