### ISSUE TITLE
Misparsing License: field from upstream tarball's included spec file

### ISSUE THREAD

**Issue by bwarden** [clearlinux/autospec#189]
Upstream tarball https://github.com/mozilla/rr/archive/5.2.0.tar.gz contains a spec file, in which:
```
License:        @CPACK_RPM_PACKAGE_LICENSE@
```

Autospec attempts to interpret this as a valid license specifier, resulting in adding "@CPACK_RPM_PACKAGE_@" (note "LICENSE" trimmed) to the License field in the spec file it generates.

**Comment by bryteise** [comment]
Fixed via #197
