### ISSUE TITLE
Fails to build Perl packages which use Module::Build::Compat

### ISSUE THREAD

**Issue by bwarden** [clearlinux/autospec#191]
Some Perl packages use Module::Build::Compat to provide both Build.PL and Makefile.PL. autospec attempts Makefile.PL first, then falls back to Build.PL. For such packages, Makefile.PL requires Module::Build, but the buildreq is not added automatically because the dependency on Module::Build is not detected from the Makefile.PL output.

I have two potential fixes to offer, either of which should be sufficient:
- Add a pattern to simple_pats to match the failure string from Makefile.PL and add perl(Module::Build) to buildreqs
- Switch the order in write_cpan_pattern to attempt Build.PL before Makefile.PL (because the dependency is correctly detected when executing Build.PL)

Packages that only provide Build.PL seem to work fine, as do packages that provide only Makefile.PL and don't require Module::Build.

**Comment by fenrus75** [comment]
real fix is to just add Modules-Build to buildreq-perl and always have it,
it does not hurt to have it there
