### ISSUE TITLE
cmake -D args cannot be specified on multiple line in cmake_args file.

### ISSUE THREAD

**Issue by asifhg** [clearlinux/autospec#195]
When cmake -D args are specified in the cmake_args file on multiple lines, make autospec invokes the cmake cmdline with all the args concatenated into a single string without any space char separating the args.
Here is an example to demonstrate.

**.../clearlinux/packages/example/cmake_args:**
```
-DABC="abc"
-DXYZ="xyz"
```
**Shell:**
```
make autospec ;
```
**.../clearlinux/packages/example/results/logs/build.log:**
```
...
cmake -DABC=abc-DXYZ=xyz ;
...
```
Notice no spaces between -D arg/value pairs on the cmake cmdline.

**Comment by bryteise** [comment]
Fixed in #196
