### ISSUE TITLE
autospec uses "tar -xf" to expand any/all archives.

### ISSUE THREAD

**Issue by asifhg** [clearlinux/autospec#198]
autospec instructs rpmbuild via the *.spec file, in the %prep section, to unarchive all/any archives via "tar -xf".

This "tar -xf" is hardcoded in:
autospec/specfiles.py:write_prep()

**Comment by fenrus75** [comment]
..... can you elaborate why this is a problem?

**Comment by asifhg** [comment]
Sometimes an archive file format is *.zip. So the %prep spec in *.spec should be:
unzip %{SOURCE1}
instead of:
tar -xf %{SOURCE1}
NOTE:
%{SOURCE1} expands to the location of the archive file.

**Comment by fenrus75** [comment]
ok that makes sense ..
