### ISSUE TITLE
Auto-detect "check" command when using meson

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/autospec#208]

**Comment by bryteise** [comment]
Currently it just always runs check right? Did you want to have this only run when tests are available?

**Comment by cmarcelo** [comment]
It only have a check block if we provide a command file. I think we can look at the meson build files and if “test(“ pattern is found, have a default ninja test call.

For the typical use cases it will make the command file unnecessary, e.g. we can remove the explicit command file from casync package.

Command file I mean the make_check_command.

**Comment by phmccarty** [comment]
I will be opening a PR soon to implement the autodetection.
