### ISSUE TITLE
Make archive support independent of file type

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#225]
Autospec has always supported tarballs for its "archives" feature, and it recently learned how to extract zip files via the rpm %setup macro (see #200).

However, it would be nice to loosen the restriction for archives to support any file type. For the archive types autospec knows how to extract, it can extract them using the current semantics, otherwise it can leave them untouched and available to reference via `%{SOURCE1}`, `%{SOURCE2}`, etc.

**Comment by bryteise** [comment]
So we have a design around only supporting a subset of file types in the SOURCE# listing that are not archives. The reason being we want to avoid enabling files being easily injected into the package that could be anything and do anything and not be something that a reviewer could easily spot (install a source file directly into the filesystem that is an archive, could be a binary, could be a config, who knows and unless you inspect the archive itself, it won't be something you see in a diff). I'm not against selective defaults for certain file types but those should be handled like how systemd units are.

**Comment by phmccarty** [comment]
This feature request conflicts with the design @bryteise describes, so I am closing it.
