### ISSUE TITLE
options.conf allow_test_failures = true not always respected

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/autospec#254]
autospec fails (for example, when running in perl-Feed-Find) due to some failing tests with an error:

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.X9gxFI (%check)

This in spite of options.conf containing:
"allow_test_failures = true"

The spec file itself contains:
make TEST_VERBOSE=1 test

although I would expect something like:

make TEST_VERBOSE=1 test || :

**Comment by bryteise** [comment]
Should be fixed now.

**Comment by jurobystricky** [comment]
Thanks. Works fine now.
