### ISSUE TITLE
`make check` unreadable

### ISSUE THREAD

**Issue by ahkok** [clearlinux/autospec#269]
Even if it passes, `make check` produces 1806 lines of output. I can't make it pass locally, but it passes in travis? This isn't conducive to even looking at `make check` locally, and should be addressed. Because people should run it locally first and not have to force push many times to try and resolve CI errors.

**Comment by bryteise** [comment]
Yea, we are using a new version of pylint on compared to the Ubuntu version running in travis and new lints were added causing local failures. Need to go and cleanup the new lint nitpicks but as you have seen it a ton of work =P.

**Comment by bryteise** [comment]
Also make check and make unittests are split and unittests are the thing we pay most attention to at the moment (should fix that not being run for make check...).

**Comment by bryteise** [comment]
Cleaned up with #301
