### ISSUE TITLE
Make package integrity verification error more user friendly

### ISSUE THREAD

**Issue by bktan8** [clearlinux/autospec#296]
In CLR 26010, autospec spits out these 404 errors when it can't find a signature file.  

Performing package integrity verification

INFO   : None of 0.13.0.tar.gz.(asc|sig|sign|sha256) is found in .
(22, 'The requested URL returned error: 404 Not Found')
(22, 'The requested URL returned error: 404 Not Found')
(22, 'The requested URL returned error: 404 Not Found')

I know they are harmless, but it would be nice to put a more user friendly message such "Can't find signature file for this package, but proceeding with build..."

**Comment by fenrus75** [comment]
or at least print the actual URL

**Comment by phmccarty** [comment]
Issue addressed with #299
