### ISSUE TITLE
Filenames with spaces must be quoted in %files

### ISSUE THREAD

**Issue by bwarden** [clearlinux/autospec#32]
CHIRP (http://trac.chirp.danplanet.com/chirp_daily/LATEST/chirp-daily-20171013.tar.gz) creates data files with spaces in their names (e.g. `/usr/share/chirp/stock_configs/US Calling Frequencies.csv`). The generated spec file currently does not quote the filename in `%files data` as required by rpmbuild.

**Comment by phmccarty** [comment]
+1

Note that implementation of the quoting support must account for special macros that may be present in order to correctly quote the line.

For example, if a directory is installed and annotated with `%dir`, then the quoting would look like `%dir "/path/to/dir with spaces"`.
