### ISSUE TITLE
meson_pattern:  test command is populated wrong in spec

### ISSUE THREAD

**Issue by chivakker** [clearlinux/autospec#321]
when running

`$ make autospec` or `$ make autospecnogit`

and the package has meson and autotools buildsystem, autospec will pick meson properly.  When writing spec file it includes a %check section that will have something like this:

`%check
...
make VERBOSE=1 -j4 check`

For meson the command should be

`check
...
ninja test -C builddir`

**Comment by phmccarty** [comment]
Related to #208

**Comment by phmccarty** [comment]
I think we should mark this as a duplicate of #208, since autospec never autodetected meson test suites before.
