### ISSUE TITLE
meson: test won't be reported in testresults file

### ISSUE THREAD

**Issue by chivakker** [clearlinux/autospec#323]
Compiled igt-gpu-tools with autospec, The build finished successfully and the test command will do its job.  Although at the end testresults won't report properly

i.e. output from build.log

249/252 assembler: test/rndz                    OK       0.01 s
250/252 assembler: test/lzd                     OK       0.01 s
251/252 assembler: test/not                     OK       0.02 s
252/252 assembler: test/immediate               OK       0.01 s
Ok:                  246
Expected Fail:         6
Fail:                  0
Unexpected Pass:       0
Skipped:               0
Timeout:               0
Full log written to /builddir/build/BUILD/igt-gpu-tools-1.23/builddir/meson-logs/testlog.txt
+ exit 0

Unfortunately the output of testresults is

$ cat ./testresults 
Total : 0
Pass : 0
Fail : 0
Skip : 0
XFail : 0

There's a parsing problem introduced recently in autospec.

**Comment by phmccarty** [comment]
I have a PR that will be ready soon that improves meson test result reporting.
