### ISSUE TITLE
Do not create/update ChangeLog if giturl setting is defined

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#341]
Because autospec adds `git shortlog` output to commits when the `giturl` setting is defined in options.conf, creating or updating the ChangeLog is usually not very useful in this situation. If one wants more detail than that provided by the shortlog, output from the appropriate `git log`, `git log -p`, or other commands can be examined instead.

**Comment by bryteise** [comment]
I was thinking about completely ignoring the changelog eventually but I'm going to do a first pass with just ignoring on giturl being set first and we'll go from there.

**Comment by phmccarty** [comment]
Resolved with #342
