### ISSUE TITLE
look for verification pattern <pkg>-<version>.sha256sum

### ISSUE THREAD

**Issue by mrkz** [clearlinux/autospec#37]
This is used by some gnome projects (e.g: http://ftp.gnome.org/pub/GNOME/sources/rest/0.8/), but in this particular case, autospec currently looks for
```
rest-0.8.1.tar.xz.asc
rest-0.8.1.tar.xz.sha256
```
where none of those are available, but `rest-0.8.1.sha256sum` is.

**Comment by phmccarty** [comment]
The `rest` package pulls from https://download.gnome.org/sources/rest/0.8/rest-0.8.1.tar.xz now, and autospec successfully verifies the https://download.gnome.org/sources/rest/0.8/rest-0.8.1.sha256sum file.

Looks like this has already been implemented.
