### ISSUE TITLE
clang-8 failing when forcing -flto=4

### ISSUE THREAD

**Issue by chivakker** [clearlinux/autospec#378]
/usr/lib64/ccache/bin/clang   -O2 -g -feliminate-unused-debug-types
-pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector
--param=ssp-buffer-size=32 -Wformat -Wformat-security
-Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code
-Wno-error -ftree-vectorize -ftree-slp-vectorize
-Wl,--enable-new-dtags -fcf-protection=return -ffat-lto-objects
-flto=4 -m64 -march=westmere -mtune=haswell
-fasynchronous-unwind-tables -fno-omit-frame-pointer -Wp,-D_REENTRANT
-O3 -ffat-lto-objects -flto=4    -o
CMakeFiles/cmTC_48195.dir/testCCompiler.c.o   -c
/builddir/build/BUILD/blender-2.79b/clr-build/CMakeFiles/CMakeTmp/testCCompiler.c
    clang-8: error: unsupported argument '4' to option 'flto='

**Comment by phmccarty** [comment]
I think this broke when `-flto=4` was added as a default cflag. See https://github.com/clearlinux/clr-rpm-config/commit/91a17a96f6.

@fenrus75 Can you elaborate on the reason for that clr-rpm-config change?

**Comment by fenrus75** [comment]
we want lto by default, and autospec to add -fno-lto for when we don't ...

**Comment by phmccarty** [comment]
Okay, thanks. So we will need to update autospec to work correctly with the new defaults.

**Comment by chivakker** [comment]
fwiw, also

 clang-8: warning: optimization flag '-ffat-lto-objects' is not supported [-Wignored-optimization-argument]
/usr/bin/ld: ../../../../lib/libbf_dna.a: error adding symbols: archive has no index; run ranlib to add one

Not sure how to interpret this error.  I tried removing ffat-lto-objects but I'm not able to.

**Comment by chivakker** [comment]
fixed by https://github.com/clearlinux/autospec/pull/387
