### ISSUE TITLE
kdeedu-data package failing to build due to latin-1 vs UTF-8 issue

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#379]
When I try to build the latest kdeedu-data release (https://download.kde.org/stable/applications/19.04.1/src/kdeedu-data-19.04.1.tar.xz), autospec exits with an error.

The chain of events:

1. rpmbuild prints a couple of path names for `%files` that have multi-byte UTF-8 characters
2. autospec parses the build.log with latin-1 encoding, thus interpreting those multi-byte characters as multiple single-byte characters
3. autospec writes `%files` entries with the latin-1-interpreted filenames
4. rpmuild exits with an error, because it expected UTF-8-encoded filenames

There are different approaches we can take to solve this:

* Open the build log for reading in binary mode and treat each line as a `bytes` object and do all pattern matching, etc with these objects. Then when we write the spec `%files` sections, all content will be properly encoded, since we never decoded the names in the first place :-)
* Open the build log for reading with UTF-8 encoding, since it is later written with UTF-8 encoding already... Any invalid UTF-8 sequences encountered would raise errors, but I suspect they are less likely to appear in build logs compared to other data sources, like we have encountered many times in the past.

**Comment by bryteise** [comment]
I think using byte streams for text sounds miserable and would be rough on a lot of the helper functions. I think an approach where we have an read/open wrapper (implementing the content manager) that figures out the encoding is the best way to go.

**Comment by phmccarty** [comment]
I also like that approach better.

**Comment by phmccarty** [comment]
Fixed with #412
