### ISSUE TITLE
Incorrect info in tests/README.rst

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/autospec#405]
The tests/README.rst document says:
<pre>
Autospec has limited functional testing capabilities that can be invoked by running make test_autospec from the root of the autospec directory
</pre>

However, the target test_autospec was removed from the root Makefile a long time ago (1/10/2018). So "make test_autospec" from the root of the autospec directory reports:
<pre>
make: *** No rule to make target 'test_autospec'.  Stop.
<_pre>

**Comment by phmccarty** [comment]
Worth nothing that the entire tests/README.rst is out-of-date. We can simply rewrite it and/or remove a lot of the existing content.

**Comment by jurobystricky** [comment]
basically you need to run 
<pre>
make check
make unittests
</pre>
