### ISSUE TITLE
autospec generates licenses that are not SPDX

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/autospec#407]
Autospec can generate a spec file containing license not considered valid, for example
<pre>
License  : Artistic-1.0-Perl GPL+ GPL-1.0
</pre>
This will result in failing to build the RPM later on with an error:

<pre>
ERROR: License 'GPL+' is not an allowed SPDX license ID
</pre>

It is not possible to override this via control file "package-name".license.
In my particular case the offending license was pulled from an already existing spec file within the package RPM (https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/Unicode-LineBreak-2019.001.tar.gz). 
I am not aware of any clean solution to this problem.

**Comment by phmccarty** [comment]
You likely want to want to "license translation" for autospec so that it can map `GPL+` to a valid SPDX identifier (likely `GPL-2.0+`).

**Comment by phmccarty** [comment]
The license translations live in https://github.com/clearlinux/autospec/blob/master/autospec/license_translations

**Comment by jurobystricky** [comment]
Thanks. Works like charm. Do you want a PR?

**Comment by jurobystricky** [comment]
Since the GPL+ originates from a spec file and Fedora says:
( https://fedoraproject.org/wiki/Licensing:Main )
<pre>

GNU General Public License (no version)
GPL+ 
 A GPL or LGPL licensed package that lacks any statement of what  version that it's licensed under in the 
source code/program  output/accompanying docs is technically licensed under *any* version of  the GPL
or LGPL, not just the version in whatever COPYING file they  include.

</pre>
I think the mapping should be
GPL+, GPL-1.0-or-later

**Comment by fenrus75** [comment]
another option is to blacklist the string, so that other sources of license
win out....
this one feels a bit squishy in definition so likely blacklist is not a
back idea

**Comment by jurobystricky** [comment]
I agree, license_blacklist already contains "GPL", so by the same logic "GPL+"  belongs there as well.

**Comment by jurobystricky** [comment]
Blacklist GPL+
https://github.com/clearlinux/autospec/commit/3d7189ab958ef113bea7af0999deb50bbec7a11b
