### ISSUE TITLE
How to add empty directory by autospec

### ISSUE THREAD

**Issue by qzheng527** [clearlinux/autospec#408]
I know autospec currently doesn't support installing empty directories. Even if there is one empty directory creation in install_append, this empty directory won't be in the final files. But what if the empty directory are necessary to run the app?
For example, I am trying to update/autospec the elasticsearch package, without the empty directories /usr/share/elasticsearch/plugins and /usr/share/defaults/elasticsearch/scripts the elasticsearch couldn't start successfully.

**Comment by bryteise** [comment]
So it seems like elasticsearch is trying to put things in those directories which would be a violation of stateless. You'll need to teach elasticsearch to use something like /var/lib/elasticsearch/ for that instead and ideally teach elasticsearch to create the directories if not found but you can fall back to systemd tmpfiles if that looks like it won't work.

**Comment by bryteise** [comment]
That is to say, this isn't an autospec related problem so closing.
