### ISSUE TITLE
rpmbuild success should not indicate a successful build

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#419]
When rpmbuild succeeds for a given build round, this event should not indicate that the build was successful, since more build rounds may occur, and any number of problems may arise:

- New build dependencies may be added, which may lead to an unsuccessful build
- New build dependencies may be added, some of which may not exist in the repo yet

The latter case I just hit with the `R-fpc` package: rpmbuild succeeded in round 3, a build dependency `R-EMMIXskew` was added for round 4, but that package did not exist in the repo. However, because rpmbuild succeeded in the previous build round, autospec proceeded to exit gracefully and commit the results.

**Comment by phmccarty** [comment]
A change like this appears to work okay, but it is a bit hacky:

```diff
diff --git a/autospec/build.py b/autospec/build.py
index 9eef841..e7c764e 100644
--- a/autospec/build.py
+++ b/autospec/build.py
@@ -245,7 +245,7 @@ def parse_build_results(filename, returncode, filemanager):
             missing_file = "/" + line.split(left)[1].strip()
             filemanager.remove_file(missing_file)

-        if line.startswith("Executing(%clean") and returncode == 0:
+        if line.startswith("Executing(%clean") and returncode == 0 and must_restart == 0:
             print("RPM build successful")
             success = 1
```

**Comment by fenrus75** [comment]
Other option is to reset that variable to zero at start of each round

**Comment by phmccarty** [comment]
> Other option is to reset that variable to zero at start of each round

Yes, I like that approach. Will open a PR for this shortly.
