### ISSUE TITLE
CVE commit message missing if previous build was aborted

### ISSUE THREAD

**Issue by clsulliv** [clearlinux/autospec#433]
Autospec compares the spec file and series file to scan for CVE patches. If the previous build was aborted, those patches are already in the spec file and thus aren't used in the commit message. It may be better to compare against the spec file as last committed instead of the dirty copy for this purpose.

**Comment by phmccarty** [comment]
Thanks for the report. This is a general issue with commit message handling, and I agree that comparing to the tree of the latest commit is a more robust solution.

**Comment by phmccarty** [comment]
Work is in progress to fix this issue.
