### ISSUE TITLE
gobuild of buildah fails

### ISSUE THREAD

**Issue by cHolzberger** [clearlinux/autospec#434]
trying to build buildah results in failing go get, the proxy settings of 127.0.0.1:9 prevents it from fetching its dependencies. 

buildah source: https://github.com/containers/buildah/
build guide: https://github.com/containers/buildah/blob/master/install.md

tried to set buildpattern to golang and golang_libpath which does not change the results.

please see: 
https://github.com/cHolzberger/clr-buildah

**Comment by bryteise** [comment]
Network access during builds is intentionally disabled. Currently #402 is being reviewed as a part of a solution to autospec dependencies though this only works when the project and its dependencies support go modules. The current solution requires the project's distribution tarball to contain the ```go mod vendor``` of their dependencies. If that isn't provided a workaround is to vendor the dependencies manually but this is really not what we want to be doing.

**Comment by phmccarty** [comment]
Closing based on the reply from @bryteise. Offline builds are a requirement for Clear Linux OS packages.
