### ISSUE TITLE
autospec blindly changing giturl in options.conf

### ISSUE THREAD

**Issue by clsulliv** [clearlinux/autospec#477]
Doing a 'make autospec' on ghostscript right now results in this change in options.conf:

-giturl = https://github.com/ArtifexSoftware/ghostpdl-downloads.git
+giturl = https://github.com/ArtifexSoftware/ghostscript.git

Unfortunately the old URL is more valid than the new URL, as the latter repo does not exist.

**Comment by phmccarty** [comment]
Looks like autospec should not modify `giturl` value if it already set. Definitely a bug.
