### ISSUE TITLE
Cannot resolve dependency name: buildreq-distutils

### ISSUE THREAD

**Issue by mikoim** [clearlinux/autospec#519]
Have Clear Linux dropped legacy Python support? There is no ``buildreq-distutils`` package in current repository.
https://download.clearlinux.org/releases/current/clear/x86_64/os/Packages/

```
[FATAL] Cannot resolve dependency name: buildreq-distutils
```

**Comment by bryteise** [comment]
We've largely dropped python2 from the distro and no longer build python2 packages.

**Comment by bryteise** [comment]
Err packages that use python2 build systems I should say.

**Comment by mikoim** [comment]
@bryteise All right. Thank you.
