### ISSUE TITLE
directories included in file list

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/autospec#52]
Occasionally (and unpredictably and un-reproducibly) we see directories being added to the file list.

**Comment by phmccarty** [comment]
A patch was added to the Clear Linux 'rpm' package recently that was intended to address this issue.

https://github.com/clearlinux-pkgs/rpm/commit/cd19a99148b64e5123207194a2dcf3c1186aa3ed

**Comment by matthewrsj** [comment]
That patch is a guess  to solve a transient problem, I still think autospec could be excluding directories. I'll reply in #58 to your comment about `%dir` files.

**Comment by matthewrsj** [comment]
Fixed by #58
