### ISSUE TITLE
install_append and excluded files

### ISSUE THREAD

**Issue by anselmolsm** [clearlinux/autospec#528]
Files in exclude control file used to be removed from the .spec file using the %exclude macro. That has changed and with the current approach using rm, binaries installed by extra install commands (e.g. defined in install_append) cause error due to files installed but not packaged.

One example was the sqlite3_analyzer in tcl package, which is in exclude file but the extra make install in install_append caused the conflict described above. This [commit](https://github.com/clearlinux-pkgs/tcl/commit/b2ff6d47542ea3094d8226f3db686e89ef7313c8) temporarily removed the extra install step as a workaround to re-autospec tcl.

**Comment by phmccarty** [comment]
If `install_append` installs additional files that should be excluded, then you can `rm` them manually.

**Comment by anselmolsm** [comment]
Right. That was done later for tcl package linked above. This can be closed, probably.

**Comment by phmccarty** [comment]
With the goal of minimizing use of `install_append` scripts and making sure they behave sanely, yes, I think we should close this.

The `tcl` package is running build steps in the install section, so to resolve that issue, those steps should be performed in `%build` (somehow).
