### ISSUE TITLE
Autospec Needs to be more Robust for go.mod file

### ISSUE THREAD

**Issue by ahsan518** [clearlinux/autospec#529]
Currently make autospec throws an error if there is an extra space in file, for example:

https://github.com/intel/cri-resource-manager/commit/02806fd60c823de8716d553f3d8c58bc183da7a9

I believe it would be better if we can surpass this check so that it doesn't throws IndexError: list index out of range

**Comment by bryteise** [comment]
Was that go.mod file manually edited? My understanding is it should only be generated.

**Comment by phmccarty** [comment]
The go module support in autospec is no longer enabled by default, so I will close this. If you need the go module support, set the build pattern to `golang-dep`.

If you are using that pattern and still encountering problem, feel free to reopen, or file a new issue.
