### ISSUE TITLE
Bitbake infile parser

### ISSUE THREAD

**Issue by Gabib32** [clearlinux/autospec#53]
The infile parser will scrape a bitbake file and enhance aspects of the specfile created tarball static analysis. It will fill in gaps the static analysis may not gather, and provide more specific information including regarding dependencies, requirements, and other options. The purpose it to prevent additional human interaction.

Key components:
* Allow input to be a url, directory (containing multiple .bb or .inc files), or a path to a file
* Scrape the .bb / .inc files and store variables to memory
* Write significant variables to specfile for autospec build

**Comment by matthewrsj** [comment]
Another goal of this feature is for it to be extensible enough that it is easy to add parsing for other recipe types, such as debian.

**Comment by matthewrsj** [comment]
Initial implementation completed in #68. @Gabib32 if there are any features that need to be added to infile parsing feel free to add them in another issue.
