### ISSUE TITLE
FCFLAGS warnings

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/autospec#538]
Autospec assumes Fortran flags are the same as CFLAGS, as can be seen in spec files::

<pre>
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
</pre>

The assumption is (no longer?) valid, as can be witnessed by the warnings at build time:

<pre>
f951: Warning: command line option ‘-Wformat=1’ is valid for C/C++/ObjC/ObjC++ but not for Fortran
f951: Warning: command line option ‘-Wformat-security’ is valid for C/C++/ObjC/ObjC++ but not for Fortran
</pre>

**Comment by phmccarty** [comment]
This has always been the assumption.

**Comment by jurobystricky** [comment]
Apparently no longer valid assumption. Although the warnings are harmless, the problem is, some builds interpret any warnings as errors.

**Comment by phmccarty** [comment]
This issue was resolved with #598.
