### ISSUE TITLE
Build log parsing too slow for digikam

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#545]
There was a report that autospec takes 2+ hours to parse the build log for the [digikam package](https://github.com/clearlinux-pkgs/digikam). The build log parsing strategy should be re-examined to better optimize this packaging step.

**Comment by bryteise** [comment]
I'm closing this as the motivating package digikam looks like it had a bit of a bug in logging build output creating highly unusual line lengths causing autospec's regex matching to be very slow. There are some packages (nodejs in particular) with very long build logs (~3 million lines, the vast majority are in the hundreds of thousands or less) but autospec handles those fairly well (under 10 minutes or so to parse).
