### ISSUE TITLE
Autospec is detecting some warning as files to install

### ISSUE THREAD

**Issue by clsulliv** [clearlinux/autospec#547]
Trying to upgrade the git package today, I ran into this in the spec file when the build failed:

```
 %files
 %defattr(-,root,root,-)
+"Duplicate build-id, stat /builddir/build/BUILDROOT/git-2.24.1-156.x86_64/usr/share/debug/.build-id/f7/86ddaef74f27c1803a3ff86b5a0294e63c737f: No such file or directory"
+"Duplicate build-id, stat /builddir/build/BUILDROOT/git-2.24.1-156.x86_64/usr/share/debug/.build-id/fa/660e68fc0c6d4ed1483b5e6d1a228a9b3b36f8: No such file or directory"
```

Looking at round1-build.log I see:
```
Processing files: git-debuginfo-2.24.1-156.x86_64
warning: Duplicate build-id, stat /builddir/build/BUILDROOT/git-2.24.1-156.x86_64/usr/share/debug/.build-id/fa/660e68fc0c6d4ed1483b5e6d1a228a9b3b36f8: No such file or directory
```

With that warning repeated many times.

And a bit further down:
```
warning: Empty %files file /builddir/build/BUILD/git-2.24.1/abifiles.list
error: Installed (but unpackaged) file(s) found:
   /usr/bin/git
<snip>
      /usr/share/perl5/Git/SVN/Utils.pm
    Duplicate build-id, stat /builddir/build/BUILDROOT/git-2.24.1-156.x86_64/usr/share/debug/.build-id/fa/660e68fc0c6d4ed1483b5e6d1a228a9b3b36f8: No such file or directory
    Duplicate build-id, stat /builddir/build/BUILDROOT/git-2.24.1-156.x86_64/usr/share/debug/.build-id/fa/660e68fc0c6d4ed1483b5e6d1a228a9b3b36f8: No such file or directory

```

**Comment by phmccarty** [comment]
Thanks for the report! This behavior is a result of moving to rpm 4.14, and autospec needs to adapt asap.

**Comment by phmccarty** [comment]
@dorileo This is another warning that rpm 4.14 may emit related to build-id problems.

**Comment by ZhengW-99** [comment]
the same error occurs!
`
error: Installed (but unpackaged) file(s) found:
   /usr/local/nginx/conf/fastcgi.conf
   /usr/local/nginx/conf/fastcgi.conf.default
   /usr/local/nginx/conf/fastcgi_params
   /usr/local/nginx/conf/fastcgi_params.default
   /usr/local/nginx/conf/koi-utf
   /usr/local/nginx/conf/koi-win
   /usr/local/nginx/conf/mime.types
   /usr/local/nginx/conf/mime.types.default
   /usr/local/nginx/conf/nginx.conf
   /usr/local/nginx/conf/nginx.conf.default
   /usr/local/nginx/conf/scgi_params
   /usr/local/nginx/conf/scgi_params.default
   /usr/local/nginx/conf/uwsgi_params
   /usr/local/nginx/conf/uwsgi_params.default
   /usr/local/nginx/conf/win-utf
   /usr/local/nginx/html/50x.html
   /usr/local/nginx/html/index.html
   /usr/local/nginx/sbin/nginx
    Installed (but unpackaged) file(s) found:
   /usr/local/nginx/conf/fastcgi.conf
   /usr/local/nginx/conf/fastcgi.conf.default
   /usr/local/nginx/conf/fastcgi_params
   /usr/local/nginx/conf/fastcgi_params.default
   /usr/local/nginx/conf/koi-utf
   /usr/local/nginx/conf/koi-win
   /usr/local/nginx/conf/mime.types
   /usr/local/nginx/conf/mime.types.default
   /usr/local/nginx/conf/nginx.conf
   /usr/local/nginx/conf/nginx.conf.default
   /usr/local/nginx/conf/scgi_params
   /usr/local/nginx/conf/scgi_params.default
   /usr/local/nginx/conf/uwsgi_params
   /usr/local/nginx/conf/uwsgi_params.default
   /usr/local/nginx/conf/win-utf
   /usr/local/nginx/html/50x.html
   /usr/local/nginx/html/index.html
   /usr/local/nginx/sbin/nginx
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
`

**Comment by fenrus75** [comment]
for this case we don't allow files in /usr/local in packages... so this is
a correct refusal by autospec
