### ISSUE TITLE
profile_payload gets read even if pgo is false

### ISSUE THREAD

**Issue by puneetse** [clearlinux/autospec#548]
As reported by @bwarden  the behavior of the pgo flag in options.conf can be inconsistent. It looks like if a `profile_payload` file exists in the directory it gets read and used, even if `pgo = false` is set in options.conf 

This scenario could occur if you tried autospec a package with pgo but later decided they did not want to use it or encountered bugs.

A more consistent behavior would be to have the `profile_payload` file only read if `pgo = true`. A warning could be displayed to the user if `pgo = false` but the `profile_payload` file exists or vice versa. 

Sources:
https://github.com/clearlinux/autospec/blob/196235ca223da095d58a604a93dfdde336106ad1/autospec/config.py#L978

https://github.com/clearlinux/autospec/blob/cd2fcdfc595eaba2974fefee0adc7fc6754b82f5/autospec/specfiles.py#L623

**Comment by puneetse** [comment]
Complimentary to this, @phmccarty did an audit of clearlinux packages to ensure packages that actually have `profile_payload` have `pgo = true` set.

**Comment by rossburton** [comment]
Is this as simple as https://github.com/rossburton/autospec/commit/49277553e55b6dfefcc7d7e1a75350039a5ce154?

**Comment by bryteise** [comment]
@rossburton looks like it is to me.

**Comment by phmccarty** [comment]
@rossburton yes, that looks like the correct fix
