### ISSUE TITLE
PyPI name clash

### ISSUE THREAD

**Issue by jayvdb** [clearlinux/autospec#553]
https://pypi.org/project/AutoSpec/ has recently been taken by https://github.com/kathleenhoza/autospec

Time to find a new name, and publish to lock in ownership of the name?

**Comment by phmccarty** [comment]
Hi, thanks for the notice!

I'm not sure this project will ever be published to PyPI, so I don't think we need to bother changing the name. "autospec" is a generic enough name that it is bound to have collisions. Another use of the term is in Python's [unittest.mock](https://docs.python.org/3/library/unittest.mock.html) package, and it has a completely different meaning.
