### ISSUE TITLE
False positive "FAIL" in count.py

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/autospec#555]
The following 
<pre>
match = re.search(r"(---\s+)?FAIL:?\s*", line)
</pre>
For example, this line will match as FAIL:
<pre>
XFAIL: t0001-basic.sh 2 - pretend known breakage # TODO known breakage
</pre>

**Comment by phmccarty** [comment]
count.py needs a lot of work, but I suppose the simple fix is to `r"(---\s+)?[^X]?FAIL:?\s*"`?

**Comment by jurobystricky** [comment]
It should work, but it does not seem to. It still matches FAIL:
<pre>
$ python
>>> import re
>>> line="XFAIL: t5000-dshbak.sh 9 - dshbak -c can detect suffix with numera"
>>> match = re.search(r"(---\s+)?[^X]?FAIL:?\s*", line)
>>> print(match, line)
&lt;re.Match object; span=(1, 7), match='FAIL: &gt;> XFAIL: t5000-dshbak.sh 9 - dshbak -c can detect suffix with numeral
</pre>

**Comment by phmccarty** [comment]
Oh, right, because the `[^X]` is optional...

A negative lookbehind assertion should work: `r"(---\s+)?(?<!X)FAIL:?\s*"`

**Comment by jurobystricky** [comment]
Yes, this one works: FAIL matches XFAIL does not. Do you need a PR?

**Comment by phmccarty** [comment]
Yes, if you don't mind :)

**Comment by jurobystricky** [comment]
No problem, PR coming soon.

**Comment by phmccarty** [comment]
Fixed with #557
