### ISSUE TITLE
autospec overwrites giturl if autodetection fails

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#57]
If autospec cannot autodetect what the upstream git repo URL should be for a package, it will overwrite `giturl` in options.conf with a blank value, even when a value is already declared in options.conf. I would expect autospec to never overwrite the `giturl` value in this case.

**Comment by matthewrsj** [comment]
Unfortunately it is not clear that this is the cause of the bug. More research is required, but the error doesn't always show up when autodetection fails.

**Comment by phmccarty** [comment]
@matthewrsj Since I have not seen this bug recur after opening the issue, I am closing it. If it happens again, I'll make sure to provide additional details to help diagnose.
