### ISSUE TITLE
AVX2/AVX512 instructions not generated for Fortran

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/autospec#580]
When selecting "use_avx2 = true" and/or "use_avx512 = true" in options.conf,
autospec generates something like this:
<pre>
%build
...
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}

pushd ../buildavx2
export CFLAGS="$CFLAGS -m64 -march=haswell"
export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
export LDFLAGS="$LDFLAGS -m64 -march=haswell"
make  %{?_smp_mflags}
popd
pushd ../buildavx512
export CFLAGS="$CFLAGS -m64 -march=skylake-avx512 -mprefer-vector-width=512"
export CXXFLAGS="$CXXFLAGS -m64 -march=skylake-avx512 -mprefer-vector-width=512"
export LDFLAGS="$LDFLAGS -m64 -march=skylake-avx512"
make  %{?_smp_mflags}
popd
</pre>

Note that the FCFLAGS/FFLAGS are not set for avx2/avx512 builds, hence any Fortran code is compiled  with "-march=westmere" (inherited from the base build). I don't assume this is by design. AFAIK there is a lot of number crunching Fortran code that would benefit greatly from AVX2 and/or AVX512 instructions.

**Comment by phmccarty** [comment]
This issue was resolved with #598.
