### ISSUE TITLE
Out-of-tree build required for latest gdb release

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#611]
The latest release of gdb (9.1) fails to autospec; the configure script exits with an error because it is being called in-tree (`./configure`) rather than out-of-tree (`../configure` or elsewhere).

Two ideas to resolve this have been proposed thus far:

- Default to run out-of-tree builds for any project that uses autotools. For projects that have a toplevel `configure.ac` and `Makefile.am`, an out-of-tree build is likely to succeed. But for projects that use only part of the autotools suite, like gdb, it's not as safe an assumption, since makefiles might be handwritten and might break for the out-of-tree scenario. Regardless, autospec must provide an option to opt-out of the default behavior, switching to an in-tree build.

- Keep the current in-tree builds for the autotools-based patterns, and provide an opt-in option to switch to an out-of-tree build.

**Comment by bryteise** [comment]
I don't mind whatever way we default, it is a simple switch in options.conf either way. It sounds like out-of-tree is common enought o make that the default.

**Comment by phmccarty** [comment]
Since the time I opened this issue, `gdb` no longer requires an out-of-tree build. Closing.
