### ISSUE TITLE
question: how infile handler works?

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/autospec#645]
It's documented that `autospec` could accept a directory of URLs as argument to `--infile`, which is handled by `infile_reader` function:

https://github.com/clearlinux/autospec/blob/b110b315e2bec7fb9629ca176b5bb59a05b70f2f/autospec/infile_handler.py#L130-L140

But I cannot understand how this could work.

`infile_reader` calls `file_handler`, which in turn calls `check_url_content`:

https://github.com/clearlinux/autospec/blob/b110b315e2bec7fb9629ca176b5bb59a05b70f2f/autospec/infile_handler.py#L146-L147

https://github.com/clearlinux/autospec/blob/b110b315e2bec7fb9629ca176b5bb59a05b70f2f/autospec/infile_handler.py#L112-L114

`check_url_content` sends a HEAD request to the `url`, which is the file name of a infile in a given directory.

https://github.com/clearlinux/autospec/blob/b110b315e2bec7fb9629ca176b5bb59a05b70f2f/autospec/infile_handler.py#L64

The problem is, for a valid HTTP or HTTPS URL, it must contain the scheme `http://` or `https://`. And `/` is not a reserved character on most Linux file systems. That is, `/` cannot appear in the file name, or in the `url` passed to `check_url_content`.

The implication is,

- Suppose I do have a directory with infiles whose file names are some kind of 'URL's. They won't be valid HTTP(s) URL. And thus they won't be treated correctly. 

I think maybe this python module is not completely/correctly implemented. Correct me if I'm wrong.

---

P.S. From the commit message https://github.com/clearlinux/autospec/commit/aef3399d1058daea96af38fd86742866ece7f512, it reads that
> The --infile argument now allows a url, file, or directory of files to be passed as the input.

So probably, it was never intended to deal with a directory of URLs.

**Comment by phmccarty** [comment]
@lebensterben This is a feature we started to implement for autospec but ultimately, we never used it. So, if you see any problems with the docs or code relevant to the feature, that is why.

**Comment by phmccarty** [comment]
Resolved with #647
