### ISSUE TITLE
multiple problems regarding BitBake file parsing

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/autospec#646]
## Operator `??=` doesn't seem to be escaped correctly
Should that be `\\?\\?\\=`?
https://github.com/clearlinux/autospec/blob/b110b315e2bec7fb9629ca176b5bb59a05b70f2f/autospec/infile_bb_parser.py#L124

## Parsing order of `.inc` and `.bb` files are incorrect.
BitBake files (`.bb`, `.bbclass`, or `.inc`) uses [`include` directive] or [`require` directive] to include the contents of a `.inc` file, at the point of the directive. Suppose we have a `foo.inc`:
```bb
A = "1"
```
And if there's a `bar.bb` s.t.:
```bb
A = "2"
include foo.inc
```
Then `A` should evaluate to `"2"`. But the current implementation parses `.inc` files first, that would make `A` equal to `"1"`.

## File structures is incorrect for `.inc` files ( and `.bbclass` files )

[The documents says][file structure]
> In order for include and class files to be found by BitBake, they need to be located in a "classes" subdirectory that can be found in BBPATH.

For a correct `.bb` file which includes or requires a `.inc` or `.bbclass` file, it would put them in the correct directory. But the current implementation doesn't reads into sub-directories.

## Missing features
First, `_prepend` and `_append` is only implemented for for shell functions, but not variables.

Then, the more general `override` syntax, including [`_remove`] and [conditionals] are not implemented. These are quite fundamental.

Third, it's already stated in comments that Python functions are not scraped, which includes BitBake Style Python function, Python funcition, and anonymous Python function. It's better to put this information in manpage or documentation.

[`include` directive]: https://www.yoctoproject.org/docs/1.6/bitbake-user-manual/bitbake-user-manual.html#include-directive
[`require` directive]: https://www.yoctoproject.org/docs/1.6/bitbake-user-manual/bitbake-user-manual.html#require-inclusion
[file structure]: https://www.yoctoproject.org/docs/1.6/bitbake-user-manual/bitbake-user-manual.html#locating-include-and-class-files
[`_remove`]: https://www.yoctoproject.org/docs/1.6/bitbake-user-manual/bitbake-user-manual.html#removing-override-style-syntax
[conditionals]: https://www.yoctoproject.org/docs/1.6/bitbake-user-manual/bitbake-user-manual.html#conditional-syntax-overrides

**Comment by lebensterben** [comment]
So, I propose to note in the documentation that, `autospec` only supports a subset of features of BitBake format:

- All operators
- `_prepend`, `_append`, `_remove`, and the general override syntax ( when they are implemented )
- Shell function

And don't support the others, including:
- Python function
- Dependencies
- Class variants
- Variable flags
- Events

**Comment by phmccarty** [comment]
Resolved with #647
