### ISSUE TITLE
build with older gcc

### ISSUE THREAD

**Issue by qumaciel** [clearlinux/autospec#662]
What is the recommended way of setting autospec to configure and build with older gcc, e.g., gcc-9?

**Comment by phmccarty** [comment]
For GCC 9, you can try adding `gcc9` and `gcc9-dev` to the `buildreq_add`, and add the following to `build_prepend`:
```
export CC=gcc-9
export CXX=g++-9
```

**Comment by qumaciel** [comment]
Thank you.
