### ISSUE TITLE
buildreq cache not caching fail pattern dependencies

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#729]
Attempting to update gst-plugins-bad from 1.20.0 to 1.20.1:

- autospec detects several build dependencies over the course of build rounds 1-3
- on build round 4, two unknown build dependencies are detected
- autospec exits with an error

The spec file looks correct, but `buildreq_cache` is not created... It should contain the build dependencies detected (via fail patterns) in build rounds 1-4. This was a feature added in https://github.com/clearlinux/autospec/pull/335, and it was still working in the not-too-distant past...

**Comment by bryteise** [comment]
Ah I see the problem here, I added an exit call when deps could not be resolved and that causes the cache file creation to be missed. I'll see if I can fix it up reasonably.
